"""Tests for the root action.yml and its job-summary renderer.

GitHub Marketplace reads action.yml from the repository root and nowhere
else. A syntax error, a missing required field, or a renamed input is not
caught by anything else in this repo -- it surfaces as a broken published
action in someone else's CI, which is the most expensive place to find out.

The renderer is tested hardest on the paths where no audit ran. Rendering an
empty table for a check that failed to execute would read as a clean bill of
health, which is the exact failure the service's own code is built to avoid.

`import yaml` here is deliberately hard, not `pytest.importorskip`. It used to
be the soft form, and because PyYAML was absent from requirements.txt, CI
silently skipped this entire module -- all 29 guards on the one file that has
already shipped dead-on-arrival once. A green CI run said nothing about
action.yml for as long as that lasted. If the dependency ever goes missing
again the suite must fail, not quietly shrink.
"""

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
ACTION_PATH = REPO_ROOT / "action.yml"
RENDERER_PATH = REPO_ROOT / "scripts" / "render_audit_summary.py"


def _load_renderer():
    spec = importlib.util.spec_from_file_location("render_audit_summary", RENDERER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules["render_audit_summary"] = module
    spec.loader.exec_module(module)
    return module


renderer = _load_renderer()


@pytest.fixture(scope="module")
def action():
    return yaml.safe_load(ACTION_PATH.read_text())


# --- Marketplace requirements -------------------------------------------


def test_action_yml_is_at_the_repository_root():
    """Marketplace will not publish an action defined anywhere else, and
    `uses: owner/repo@ref` only resolves a root action.yml."""
    assert ACTION_PATH.is_file()


def test_this_repo_cannot_itself_be_marketplace_published():
    """Documents the constraint rather than asserting a wish.

    Marketplace requires an action repo to contain NO workflow files. This one
    has CI, so the listing must come from the standalone repo generated by
    scripts/publish-action-repo.sh. If this ever starts failing because the
    workflows were deleted, that is a much bigger change than a publish tweak
    and should be a deliberate decision, not a silent one.
    """
    workflows = list((REPO_ROOT / ".github" / "workflows").glob("*.y*ml"))
    assert workflows, (
        "This repo no longer has workflow files. Re-check whether the action "
        "can now be published from here directly instead of via "
        "scripts/publish-action-repo.sh."
    )
    assert (REPO_ROOT / "scripts" / "publish-action-repo.sh").is_file()


def test_the_generated_marketplace_repo_has_no_workflow_files(tmp_path):
    """The one rule that silently disqualifies a Marketplace listing."""
    target = tmp_path / "generated"
    subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        check=True, capture_output=True, text=True,
    )
    files = {p.relative_to(target).as_posix() for p in target.rglob("*") if p.is_file()}
    assert files == {
        "action.yml",
        "README.md",
        "scripts/render_audit_summary.py",
        # The wallet payment path; action.yml calls it by $GITHUB_ACTION_PATH,
        # so a published copy without it fails on the one path that spends money.
        "scripts/x402_pay.py",
    }
    assert not list(target.rglob(".github/workflows/*"))


def test_the_generated_action_is_byte_identical_to_the_source(tmp_path):
    """A generated copy that can drift is the problem this replaced."""
    target = tmp_path / "generated"
    subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        check=True, capture_output=True, text=True,
    )
    assert (target / "action.yml").read_bytes() == ACTION_PATH.read_bytes()
    assert (
        (target / "scripts" / "render_audit_summary.py").read_bytes()
        == RENDERER_PATH.read_bytes()
    )


def test_the_listing_documents_every_input_and_output(tmp_path):
    """The listing is the only thing a browsing developer reads before
    deciding. An input it omits is a feature nobody knows exists; one it
    invents is a broken first impression."""
    target = tmp_path / "generated"
    subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        check=True, capture_output=True, text=True,
    )
    action = yaml.safe_load((target / "action.yml").read_text())
    readme = (target / "README.md").read_text()

    for name in action["inputs"]:
        assert f"`{name}`" in readme, f"input {name} is undocumented"
    for name in action["outputs"]:
        assert f"`{name}`" in readme, f"output {name} is undocumented"


def test_the_listing_quotes_the_real_defaults(tmp_path):
    """A listing promising `retries: 3` while the action does 2 is a support
    ticket. Only the URL default is prose ('hosted'), deliberately."""
    target = tmp_path / "generated"
    subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        check=True, capture_output=True, text=True,
    )
    action = yaml.safe_load((target / "action.yml").read_text())
    readme = (target / "README.md").read_text()

    for name, spec in action["inputs"].items():
        default = spec.get("default", "")
        if not default or default.startswith("http"):
            continue
        row = [ln for ln in readme.splitlines() if ln.startswith(f"| `{name}` |")]
        assert row, f"{name} has no table row"
        assert f"`{default}`" in row[0], (
            f"listing shows a different default for {name} than the action does"
        )


def test_the_listing_states_the_price(tmp_path):
    """It is a paid action. Burying that wastes the reader's time and ours --
    they find out at the first 402 and leave annoyed."""
    target = tmp_path / "generated"
    subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        check=True, capture_output=True, text=True,
    )
    readme = (target / "README.md").read_text()
    assert "$0.05" in readme
    assert "$0.15" in readme


def test_the_listing_does_not_assert_a_payment_rail(tmp_path):
    """Same rule as every other shipped surface: it cannot know which rails a
    deployment settles, so it links agent.json instead of naming one."""
    target = tmp_path / "generated"
    subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        check=True, capture_output=True, text=True,
    )
    readme = (target / "README.md").read_text().lower()
    assert "x402" not in readme
    assert "agent.json" in readme


def test_publish_script_refuses_to_overwrite_a_non_empty_directory(tmp_path):
    target = tmp_path / "existing"
    target.mkdir()
    (target / "keepme.txt").write_text("important")
    result = subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        capture_output=True, text=True,
    )
    assert result.returncode != 0
    assert (target / "keepme.txt").read_text() == "important"


def test_there_is_exactly_one_action_definition():
    """A second copy elsewhere in the tree drifts from the published one."""
    found = [
        p
        for p in REPO_ROOT.rglob("action.y*ml")
        if ".git" not in p.parts and "node_modules" not in p.parts
    ]
    assert found == [ACTION_PATH], f"unexpected extra action definitions: {found}"


def test_required_marketplace_fields_are_present(action):
    assert action["name"]
    assert action["description"]
    assert action["runs"]["using"] == "composite"
    # Branding is what Marketplace renders on the listing card; without it
    # the listing is rejected at publish time.
    assert action["branding"]["icon"]
    assert action["branding"]["color"]


def test_the_documented_inputs_exist_with_stable_names(action):
    """These names are a public API the moment the action is published --
    renaming one breaks every workflow that already adopted it."""
    assert set(action["inputs"]) == {
        "url",
        "api-key",
        # Added when the action learned to pay its own 402 from a funded
        # wallet, so a pipeline no longer needs a bought subscription before
        # its first useful run.
        "wallet-key",
        "max-price-usd",
        "endpoint",
        "fail-on-violation",
        "fail-on-error",
        "timeout-seconds",
        "retries",
        "base-url",
    }
    assert action["inputs"]["url"]["required"] is True


def test_api_key_is_optional_so_the_action_can_report_its_own_402(action):
    """A required api-key makes the action unusable without a key even to see
    what it costs; the 402 body is how a caller learns the price."""
    assert action["inputs"]["api-key"]["required"] is False


def test_outputs_are_wired_to_the_audit_step(action):
    for name in ("passed", "response", "http-status"):
        assert "steps.audit.outputs" in action["outputs"][name]["value"]


def test_the_action_references_the_renderer_it_ships_with(action):
    script = action["runs"]["steps"][0]["run"]
    assert "$GITHUB_ACTION_PATH/scripts/render_audit_summary.py" in script
    assert RENDERER_PATH.is_file()


def test_the_url_is_json_encoded_rather_than_interpolated(action):
    """A URL containing a quote must not be able to produce malformed JSON
    (or inject fields) into the request body."""
    script = action["runs"]["steps"][0]["run"]
    assert "json.dumps" in script
    assert '-d "{\\"url\\"' not in script


def test_4xx_responses_are_not_retried(action):
    """Retrying a 402 on a metered endpoint risks paying twice for one answer."""
    script = action["runs"]["steps"][0]["run"]
    assert "000|5*)" in script


# --- renderer: nothing ran --------------------------------------------------


def test_a_402_is_reported_as_unpaid_and_unaudited():
    out = renderer.render(None, "402", "bundle", "https://example.com")
    assert "Payment required" in out
    assert "no audit was performed" in out.lower()


def test_a_failed_request_is_never_rendered_as_a_pass():
    out = renderer.render(None, "000", "bundle", "https://example.com")
    assert "✅" not in out
    assert "never completed" in out


def test_an_unparseable_body_is_flagged_rather_than_rendered_empty(tmp_path):
    path = tmp_path / "response.json"
    path.write_text("<html>gateway error</html>")
    body, error = renderer._load(str(path))
    assert body is None
    assert "not JSON" in error


def test_a_missing_dimension_is_reported_as_did_not_run():
    body = {"pass": False, "wcag": {"pass": None, "violations": []}}
    out = renderer.render(body, "200", "bundle", "https://example.com")
    assert "did not run" in out


# --- renderer: results ------------------------------------------------------


def test_violations_are_rendered_with_rule_impact_and_help_link():
    body = {
        "pass": False,
        "wcag": {
            "pass": False,
            "violations": [
                {
                    "id": "color-contrast",
                    "impact": "serious",
                    "nodes_affected": 4,
                    "help": "Elements must have sufficient contrast",
                    "help_url": "https://dequeuniversity.com/rules/axe/color-contrast",
                }
            ],
        },
    }
    out = renderer.render(body, "200", "bundle", "https://example.com")
    assert "`color-contrast`" in out
    assert "serious" in out
    assert "dequeuniversity.com" in out


def test_findings_are_rendered_for_the_non_axe_dimensions():
    body = {
        "pass": False,
        "security": {
            "pass": False,
            "findings": [{"id": "missing-hsts", "severity": "high", "detail": "No HSTS header"}],
        },
    }
    out = renderer.render(body, "200", "bundle", "https://example.com")
    assert "`missing-hsts`" in out
    assert "No HSTS header" in out


def test_a_single_dimension_response_renders_its_top_level_results():
    """A /audit/wcag call returns violations at the top level, not nested."""
    body = {"pass": False, "violations": [{"id": "image-alt", "impact": "critical"}]}
    out = renderer.render(body, "200", "wcag", "https://example.com")
    assert "`image-alt`" in out


def test_long_result_lists_are_truncated_with_a_count():
    body = {
        "pass": False,
        "wcag": {"pass": False, "violations": [{"id": f"rule-{i}"} for i in range(40)]},
    }
    out = renderer.render(body, "200", "bundle", "https://example.com")
    assert "and 25 more" in out


def test_pipes_in_findings_cannot_break_the_markdown_table():
    body = {
        "pass": False,
        "seo": {"pass": False, "findings": [{"id": "title", "detail": "a | b\nc"}]},
    }
    out = renderer.render(body, "200", "bundle", "https://example.com")
    row = [line for line in out.splitlines() if "`title`" in line][0]
    assert "\\|" in row  # the literal pipe is escaped
    # Once escaped pipes are removed, only the 4 cell delimiters remain, so
    # the finding cannot open extra columns. The newline is flattened too.
    assert row.replace("\\|", "").count("|") == 4
    assert "a \\| b c" in row


def test_a_clean_audit_renders_a_pass():
    body = {"pass": True, "wcag": {"pass": True, "violations": []}}
    out = renderer.render(body, "200", "bundle", "https://example.com")
    assert "✅ pass" in out
    assert "No issues found." in out


def test_the_renderer_runs_as_a_script_and_never_crashes_the_step(tmp_path):
    """The action calls this with `|| true`, but a traceback in the summary is
    still noise the adopter has to reason about."""
    path = tmp_path / "response.json"
    path.write_text(json.dumps({"pass": True}))
    result = subprocess.run(
        [sys.executable, str(RENDERER_PATH), "--response", str(path),
         "--status", "200", "--endpoint", "bundle", "--url", "https://example.com"],
        capture_output=True, text=True,
    )
    assert result.returncode == 0
    assert "HubVibe Site Compliance Audit" in result.stdout


def test_the_renderer_survives_a_missing_response_file(tmp_path):
    result = subprocess.run(
        [sys.executable, str(RENDERER_PATH), "--response", str(tmp_path / "nope.json"),
         "--status", "000", "--endpoint", "bundle", "--url", "https://example.com"],
        capture_output=True, text=True,
    )
    assert result.returncode == 0
    assert "✅" not in result.stdout


def test_pyyaml_is_declared_so_this_module_cannot_silently_skip_again():
    """The pin in requirements.txt is what makes every test above actually run
    in CI.

    Deleting it does not fail anywhere else: PyYAML arrives transitively in
    plenty of environments, so a local run stays green while CI -- which
    installs only requirements.txt -- collects 29 fewer tests and reports a
    pass. That is precisely how the guards on action.yml went unrun, and how
    two sessions came away with two different, both-defensible test counts.
    """
    declared = (REPO_ROOT / "requirements.txt").read_text().lower()
    assert "pyyaml" in declared, (
        "PyYAML is missing from requirements.txt; CI will skip this whole "
        "module and report a green run that proves nothing about action.yml"
    )


def test_the_listing_ships_a_complete_workflow_not_only_a_step(tmp_path):
    """A step fragment is not something a developer can act on -- they still
    have to know the workflow scaffolding around it. Adoption is what turns
    into paid call volume, and the difference between "here is a step" and
    "here is the file" is a real share of it.
    """
    target = tmp_path / "listing"
    subprocess.run(
        ["bash", str(REPO_ROOT / "scripts" / "publish-action-repo.sh"), str(target)],
        check=True,
        capture_output=True,
    )
    readme = (target / "README.md").read_text()

    assert "on:" in readme and "push:" in readme, (
        "the listing must show a workflow with its triggers, not just a step"
    )
    assert "jobs:" in readme and "runs-on:" in readme
    assert ".github/workflows/" in readme, "say where the file goes"

    # The listing must lead with a payment path the reader can actually
    # complete. A key cannot be bought on an x402-only deployment, so a
    # quickstart built on `api-key` sends every Marketplace visitor to a
    # doorway that answers 501 -- the wallet pays the 402 itself and needs
    # no account, which is the whole premise of a machine-payable API.
    assert "secrets.HUBVIBE_WALLET_KEY" in readme
    assert "USDC on Base" in readme, "say how to fund the wallet the quickstart needs"
    assert "api-key" in readme, "the prepaid-key alternative must still be documented"


def test_the_shipped_workflow_calls_the_action_rather_than_curl():
    """integrations/github_action.yml is copied into consumer repos. When it
    hand-rolled the HTTP call it duplicated the action's retry policy, its
    4xx no-retry rule (a metered endpoint must never be paid twice for the
    same answer) and its JSON encoding of the target URL -- three behaviours
    that then had to be maintained by whoever copied it."""
    import yaml

    workflow = yaml.safe_load(
        (REPO_ROOT / "wcag-audit-engine" / "integrations" / "github_action.yml").read_text()
    )
    # PyYAML parses a bare `on:` key as the boolean True.
    triggers = workflow.get("on", workflow.get(True))
    assert "push" in triggers, "the CI gate must run on push"

    steps = workflow["jobs"]["audit"]["steps"]
    action_step = next((s for s in steps if "uses" in s), None)
    assert action_step is not None, "the workflow must call the published action"
    assert action_step["uses"].startswith("Its-fortunatefolly/hubvibe-audit-action@")

    assert not any("curl" in str(s.get("run", "")) for s in steps), (
        "no hand-rolled HTTP call -- the action already owns that logic"
    )

    endpoint = action_step["with"]["endpoint"]
    assert endpoint in {"wcag", "seo", "security", "performance", "bundle"}, endpoint
